### ISSUE TITLE
Kernel crash with code that runs fine in Scala interpreter

### ISSUE THREAD

**Issue by cliburn** [jove-sh/jove-scala#1]
While working through 99 Scala problems, the solution to problem 12 causes the kernel to crash

**P12** Decode a run-length encoded list.

Given a run-length code list generated as specified in problem P10, construct its uncompressed version.

Example:
```scala
scala> decode(List((4, 'a), (1, 'b), (2, 'c), (2, 'a), (1, 'd), (4, 'e)))
res0: List[Symbol] = List('a, 'a, 'a, 'a, 'b, 'c, 'c, 'a, 'a, 'd, 'e, 'e, 'e, 'e)
```

// Works in Scala interpreter but crashes kernel in Notebook
```scala
def decode[A](xs: List[(Int, A)]): List[A] = 
    for {
        (n, x) <- xs
        i <- 1 to n
    } yield x
```

```scala
scala> decode(List((4, 'a), (1, 'b), (2, 'c), (2, 'a), (1, 'd), (4, 'e)))
res3: List[Symbol] = List('a, 'a, 'a, 'a, 'b, 'c, 'c, 'a, 'a, 'd, 'e, 'e, 'e, 'e)
````

System:
OS X 10.9.5

Version info:
IPython notebook 3.1
Scala 2.11

Error message:
```
[I 12:28:32.928 NotebookApp] Saving file at /NinetyNine.ipynb
Done fetching / updating artifacts
Exception in thread "Thread-74" Exception in thread "Thread-75" org.zeromq.ZMQException: Errno 156384765 : Context was terminated
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1344)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1209)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1193)
	at jove.kernel.socket.zmq.ZMQMessageSocket.send(ZMQMessageSocket.scala:95)
	at jove.kernel.server.InterpreterServer$$anonfun$1.apply(InterpreterServer.scala:45)
	at jove.kernel.server.InterpreterServer$$anonfun$1.apply(InterpreterServer.scala:45)
	at jove.kernel.interpreter.InterpreterHandler$.jove$kernel$interpreter$InterpreterHandler$$sendStream(InterpreterHandler.scala:57)
	at jove.kernel.interpreter.InterpreterHandler$$anonfun$jove$kernel$interpreter$InterpreterHandler$$execute$2$$anonfun$stream$1$1.apply(InterpreterHandler.scala:107)
	at jove.kernel.interpreter.InterpreterHandler$$anonfun$jove$kernel$interpreter$InterpreterHandler$$execute$2$$anonfun$stream$1$1.apply(InterpreterHandler.scala:107)
	at jove.scala.imainlike.Capture$$anon$1.run(Capture.scala:11)
org.zeromq.ZMQException: Errno 156384765 : Context was terminated
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1344)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1209)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1193)
	at jove.kernel.socket.zmq.ZMQMessageSocket$$anonfun$send$1.apply(ZMQMessageSocket.scala:94)
	at jove.kernel.socket.zmq.ZMQMessageSocket$$anonfun$send$1.apply(ZMQMessageSocket.scala:94)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at jove.kernel.socket.zmq.ZMQMessageSocket.send(ZMQMessageSocket.scala:94)
	at jove.kernel.server.InterpreterServer$$anonfun$1.apply(InterpreterServer.scala:45)
	at jove.kernel.server.InterpreterServer$$anonfun$1.apply(InterpreterServer.scala:45)
	at jove.kernel.interpreter.InterpreterHandler$.jove$kernel$interpreter$InterpreterHandler$$sendStream(InterpreterHandler.scala:57)
	at jove.kernel.interpreter.InterpreterHandler$$anonfun$jove$kernel$interpreter$InterpreterHandler$$execute$2$$anonfun$stream$1$1.apply(InterpreterHandler.scala:107)
	at jove.kernel.interpreter.InterpreterHandler$$anonfun$jove$kernel$interpreter$InterpreterHandler$$execute$2$$anonfun$stream$1$1.apply(InterpreterHandler.scala:107)
	at jove.scala.imainlike.Capture$$anon$1.run(Capture.scala:11)
Exception in thread "RequestsEventLoop" java.lang.AssertionError: assertion failed: List(value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp, value _1$mcI$sp)
	at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:1916)[I 12:31:34.566 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

**Comment by alexarchambault** [comment]
It works for me as is (see below). Would there be some context (code entered before, dependencies, ...?), required to make that happen?

I'm using IPython Notebook 3.0 with the archives downloaded from the links on https://github.com/jove-sh/jove-scala, and tested both 2.10 and 2.11:
![nb](https://cloud.githubusercontent.com/assets/7063723/7216396/3f3406b6-e5fe-11e4-8901-4c496be39bda.png)

**Comment by cliburn** [comment]
Thanks for the prompt response

I restarted the notebook server, and ran the cell again  - this works as in your example

However, if I try to re-execute Cell [1] again - the kernel crashes.

Thanks,

Cliburn


On April 18, 2015 at 1:09:29 PM, Alexandre Archambault (notifications@github.com<mailto:notifications@github.com>) wrote:

It works for me as is (see below). Would there be some context (code entered before, dependencies, ...?), required to make that happen?

I'm using IPython Notebook 3.0 with the archives downloaded from the links on https://github.com/jove-sh/jove-scala, and tested both 2.10 and 2.11:
[nb]<https://cloud.githubusercontent.com/assets/7063723/7216396/3f3406b6-e5fe-11e4-8901-4c496be39bda.png>

**Comment by alexarchambault** [comment]
Ok, just saw it, thanks.

I can't investigate further right now, but if you're willing to take risks, it works with the kernels from https://github.com/alexarchambault/jupyter-scala. These should supersede the ones from here soon, but they're a bit less documented (regarding dependencies, ... - it's like in https://github.com/lihaoyi/Ammonite, which it uses internally).

**Comment by cliburn** [comment]
OK - I’ll try as you suggest - just playing with learning Scala so risk is no big deal - thanks again for the great work making Scala/Spark available in Jupyter!


On April 18, 2015 at 1:24:50 PM, Alexandre Archambault (notifications@github.com<mailto:notifications@github.com>) wrote:

Ok, just saw it, thanks.

I can't investigate further right now, but if you're willing to take risks, it works with the kernels from https://github.com/alexarchambault/jupyter-scala. These should supersede the ones from here soon, but they're a bit less documented (regarding dependencies, ... - it's like in https://github.com/lihaoyi/Ammonite, which it uses internally).

**Comment by cliburn** [comment]
With jupyter-sclaa, set difference gives the wrong answer

In the interpreter
```scala

scala> val ls  = List('a, 'b, 'c, 'd, 'e, 'f).toSet

ls: scala.collection.immutable.Set[Symbol] = Set('e, 'f, 'a, 'b, 'c, 'd)


scala> val l1 = List('a, 'd).toSet

l1: scala.collection.immutable.Set[Symbol] = Set('a, 'd)


scala> ls &~ l1

res15: scala.collection.immutable.Set[Symbol] = Set('e, 'f, 'b, ‘c)

```

In the notebook

[cid:614BCF76-1BC8-488B-8F2A-5573B5C2EAC6]

On April 18, 2015 at 1:24:50 PM, Alexandre Archambault (notifications@github.com<mailto:notifications@github.com>) wrote:

Ok, just saw it, thanks.

I can't investigate further right now, but if you're willing to take risks, it works with the kernels from https://github.com/alexarchambault/jupyter-scala. These should supersede the ones from here soon, but they're a bit less documented (regarding dependencies, ... - it's like in https://github.com/lihaoyi/Ammonite, which it uses internally).

**Comment by alexarchambault** [comment]
Closing this. All of this is fixed in https://github.com/alexarchambault/jupyter-scala.
